# Generated by Django 5.0.4 on 2024-04-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_skin', '0002_alter_skin_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='imagem',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
