# Generated by Django 5.0.4 on 2024-04-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_skin', '0003_alter_skin_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='imagem',
            field=models.ImageField(blank=True, default='', upload_to='skins/covers/%Y/%m/%d/'),
        ),
    ]
